import type { BiomarkerReference } from '../types';

export const BIOMARKERS: BiomarkerReference[] = [
  {
    id: 'total_t',
    name: 'Total Testosterone',
    short_name: 'Total T',
    unit_primary: 'ng/dL',
    unit_secondary: 'nmol/L',
    conversion_factor: 0.0347,
    standard_range_low: 264,
    standard_range_high: 916,
    optimal_range_low: 500,
    optimal_range_high: 900,
    age_adjusted: true,
    description: 'The headline number — your body\'s total testosterone output.',
    high_explanation: 'Total T is high. This is generally positive, but very high levels may indicate exogenous testosterone or other conditions.',
    low_explanation: 'Total T is below optimal. This is the most common finding in men with symptoms. Lifestyle changes and further investigation are warranted.',
    category: 'hormones',
  },
  {
    id: 'free_t',
    name: 'Free Testosterone',
    short_name: 'Free T',
    unit_primary: 'pg/mL',
    standard_range_low: 5.0,
    standard_range_high: 21.0,
    optimal_range_low: 10.0,
    optimal_range_high: 20.0,
    age_adjusted: true,
    description: 'The biologically active, unbound portion of testosterone your body can actually use.',
    high_explanation: 'Free T is elevated. Generally positive, but should be considered alongside total T and SHBG.',
    low_explanation: 'Free T is low. Even with normal total T, low free T causes symptoms. Often caused by high SHBG.',
    category: 'hormones',
  },
  {
    id: 'shbg',
    name: 'Sex Hormone-Binding Globulin',
    short_name: 'SHBG',
    unit_primary: 'nmol/L',
    standard_range_low: 10,
    standard_range_high: 57,
    optimal_range_low: 20,
    optimal_range_high: 40,
    age_adjusted: false,
    description: 'Protein that binds testosterone, making it inactive. High SHBG = less usable testosterone.',
    high_explanation: 'High SHBG is binding too much of your testosterone, reducing free T. Often caused by high estrogen, thyroid issues, or aging.',
    low_explanation: 'Low SHBG may indicate insulin resistance or obesity. Can cause symptoms despite normal total T.',
    category: 'hormones',
  },
  {
    id: 'estradiol',
    name: 'Estradiol',
    short_name: 'E2',
    unit_primary: 'pg/mL',
    standard_range_low: 10,
    standard_range_high: 40,
    optimal_range_low: 15,
    optimal_range_high: 30,
    age_adjusted: false,
    description: 'Primary estrogen in men. Testosterone converts to estradiol via aromatase. The T:E2 ratio is critical.',
    high_explanation: 'Elevated estradiol can cause low libido, mood swings, and fat gain. Often associated with high body fat or alcohol use.',
    low_explanation: 'Very low estradiol can impair bone density, libido, and mood. The goal is balance, not elimination.',
    category: 'hormones',
  },
  {
    id: 'lh',
    name: 'Luteinizing Hormone',
    short_name: 'LH',
    unit_primary: 'mIU/mL',
    standard_range_low: 1.7,
    standard_range_high: 8.6,
    optimal_range_low: 3.0,
    optimal_range_high: 7.0,
    age_adjusted: false,
    description: 'Brain signal telling testes to produce testosterone. Helps identify the root cause of low T.',
    high_explanation: 'High LH with low T suggests primary hypogonadism (testicular issue). The brain is signaling but the testes aren\'t responding.',
    low_explanation: 'Low LH with low T suggests secondary hypogonadism (brain/pituitary issue). The signal isn\'t being sent.',
    category: 'hormones',
  },
  {
    id: 'fsh',
    name: 'Follicle-Stimulating Hormone',
    short_name: 'FSH',
    unit_primary: 'mIU/mL',
    standard_range_low: 1.5,
    standard_range_high: 12.4,
    optimal_range_low: 2.0,
    optimal_range_high: 8.0,
    age_adjusted: false,
    description: 'Brain hormone related to sperm production and fertility.',
    high_explanation: 'High FSH may indicate testicular dysfunction or reduced sperm production.',
    low_explanation: 'Low FSH may indicate a pituitary or hypothalamic issue.',
    category: 'hormones',
  },
  {
    id: 'prolactin',
    name: 'Prolactin',
    short_name: 'Prolactin',
    unit_primary: 'ng/mL',
    standard_range_low: 4.0,
    standard_range_high: 15.2,
    optimal_range_low: 4.0,
    optimal_range_high: 12.0,
    age_adjusted: false,
    description: 'Hormone that suppresses testosterone when elevated. Often overlooked as a cause of low T.',
    high_explanation: 'Elevated prolactin directly suppresses testosterone. Very high levels may indicate a pituitary adenoma and require an MRI.',
    low_explanation: 'Low prolactin is generally not a concern.',
    category: 'hormones',
  },
  {
    id: 'vitamin_d',
    name: 'Vitamin D (25-OH)',
    short_name: 'Vitamin D',
    unit_primary: 'ng/mL',
    standard_range_low: 30,
    standard_range_high: 100,
    optimal_range_low: 40,
    optimal_range_high: 60,
    age_adjusted: false,
    description: 'Steroid hormone precursor strongly correlated with testosterone levels.',
    high_explanation: 'Vitamin D is optimal. Maintain current supplementation/sun exposure.',
    low_explanation: 'Low Vitamin D is one of the most modifiable risk factors for low T. Supplementation is highly effective.',
    category: 'other',
  },
  {
    id: 'cortisol',
    name: 'Cortisol (Morning)',
    short_name: 'Cortisol',
    unit_primary: 'µg/dL',
    standard_range_low: 6.0,
    standard_range_high: 18.4,
    optimal_range_low: 10.0,
    optimal_range_high: 15.0,
    age_adjusted: false,
    description: 'Stress hormone that directly antagonizes testosterone. Must be drawn before 9 AM.',
    high_explanation: 'Elevated cortisol is suppressing your testosterone. Chronic stress, poor sleep, and overtraining are common causes.',
    low_explanation: 'Very low cortisol may indicate adrenal insufficiency. Consult your doctor.',
    category: 'other',
  },
  {
    id: 'tsh',
    name: 'Thyroid Stimulating Hormone',
    short_name: 'TSH',
    unit_primary: 'mIU/L',
    standard_range_low: 0.4,
    standard_range_high: 4.0,
    optimal_range_low: 1.0,
    optimal_range_high: 2.5,
    age_adjusted: false,
    description: 'Thyroid function marker. Thyroid dysfunction mimics low-T symptoms and must be ruled out.',
    high_explanation: 'Elevated TSH indicates an underactive thyroid (hypothyroidism). Symptoms mirror low T: fatigue, weight gain, brain fog.',
    low_explanation: 'Low TSH indicates an overactive thyroid (hyperthyroidism). Can cause anxiety, insomnia, and weight loss.',
    category: 'thyroid',
  },
  {
    id: 'glucose',
    name: 'Fasting Glucose',
    short_name: 'Glucose',
    unit_primary: 'mg/dL',
    standard_range_low: 70,
    standard_range_high: 99,
    optimal_range_low: 70,
    optimal_range_high: 90,
    age_adjusted: false,
    description: 'Fasting blood sugar. Insulin resistance directly suppresses testosterone.',
    high_explanation: 'Elevated fasting glucose indicates insulin resistance. This directly suppresses testosterone and increases estrogen.',
    low_explanation: 'Very low glucose (hypoglycemia) requires medical attention.',
    category: 'metabolic',
  },
  {
    id: 'hematocrit',
    name: 'Hematocrit',
    short_name: 'Hematocrit',
    unit_primary: '%',
    standard_range_low: 38.3,
    standard_range_high: 48.6,
    optimal_range_low: 41,
    optimal_range_high: 48,
    age_adjusted: false,
    description: 'Red blood cell percentage. Testosterone increases red blood cells — very high levels are a safety concern.',
    high_explanation: 'High hematocrit (above 54%) indicates polycythemia risk, which can cause blood clots. Medical evaluation required.',
    low_explanation: 'Low hematocrit may indicate anemia, which contributes to fatigue.',
    category: 'metabolic',
  },
  {
    id: 'dht',
    name: 'Dihydrotestosterone',
    short_name: 'DHT',
    unit_primary: 'ng/dL',
    standard_range_low: 30,
    standard_range_high: 85,
    optimal_range_low: 40,
    optimal_range_high: 70,
    age_adjusted: false,
    description: 'The most potent androgen. Converted from testosterone via 5-alpha reductase.',
    high_explanation: 'High DHT is associated with hair loss and prostate enlargement in susceptible individuals.',
    low_explanation: 'Low DHT may indicate finasteride use or 5-alpha reductase deficiency.',
    category: 'hormones',
  },
];

export const BIOMARKER_MAP = Object.fromEntries(BIOMARKERS.map(b => [b.id, b]));

export const CORE_PANEL_IDS = [
  'total_t', 'free_t', 'shbg', 'estradiol', 'lh', 'fsh', 'prolactin', 'hematocrit', 'glucose',
];

export const EXTENDED_PANEL_IDS = [
  'tsh', 'cortisol', 'dht', 'vitamin_d',
];

export const KEY_RATIOS = {
  te2: {
    name: 'T:E2 Ratio',
    description: 'Androgenic vs estrogenic balance. Optimal: 15–25',
    optimal_low: 15,
    optimal_high: 25,
    calculate: (totalT: number, e2: number): number => (e2 > 0 ? totalT / e2 : 0),
  },
  fti: {
    name: 'Free T Index',
    description: 'Estimates bioavailable testosterone fraction',
    optimal_low: 0.4,
    optimal_high: 1.2,
    calculate: (totalT_nmol: number, shbg: number): number =>
      shbg > 0 ? (totalT_nmol / shbg) * 100 : 0,
  },
};
